branch_whitelist = ["main"]
disable_bump_commit = false
disable_changelog = false
from_latest_tag = false
generate_mono_repository_global_tag = true
ignore_merge_commits = true
post_bump_hooks = []
post_package_bump_hooks = []
pre_bump_hooks = []
pre_package_bump_hooks = []
skip_ci = "[skip ci]"
skip_untracked = false

[git_hooks]

[commit_types]

[changelog]
authors = []
owner = "guiyomh"
path = "CHANGELOG.md"
remote = "github.com"
repository = "aicommitter"
template = ".changelog.tpl"

[bump_profiles]

[packages]
