version: "3"

env:
  CGO_ENABLED: "0"

vars:
  BIN: "{{.ROOT_DIR}}/bin"

tasks:
  # default:
  #   cmds:
  #     - task: lint
  #     - task: test

  install:
    desc: Installs aicommitter
    aliases: [i]
    sources:
      - "./**/*.go"
    cmds:
      - go install -v ./cmd/aicommitter

  setup:
    desc: Install tools needed for development
    cmds:
      - task: install:mockery
      - task: install:golangci-lint

  install:mockery:
    desc: Installs mockgen; a tool to generate mock files
    internal: true
    vars:
      MOCKERY_VERSION: v2.24.0
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/mockery | grep github.com/vektra/mockery | grep {{.MOCKERY_VERSION}}
    cmds:
      - go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}

  install:golangci-lint:
    desc: Installs golangci-lint
    internal: true
    vars:
      GOLANGCI_LINT_VERSION: v1.60.3
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/golangci-lint | grep github.com/golangci/golangci-lint | grep {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  lint:
    desc: Runs golangci-lint
    aliases: [l]
    sources:
      - "./**/*.go"
      - .golangci.yml
    cmds:
      - "{{.BIN}}/golangci-lint run"

  lint:fix:
    desc: Runs golangci-lint and fixes any issues
    sources:
      - "./**/*.go"
      - .golangci.yml
    cmds:
      - "{{.BIN}}/golangci-lint run --fix"

  test:
    desc: Runs test suite
    aliases: [t]
    deps: [install]
    cmds:
      - go test {{catLines .GO_PACKAGES}}
    vars:
      GO_PACKAGES:
        sh: go list ./...

  run:
    desc: Runs aicommitter
    aliases: [r]
    deps: [install]
    dotenv:
      - .env
    cmds:
      - aicommitter
